const actionTypes = {
  LOAD_POPULAR_MOVIES: 'LOAD_POPULAR_MOVIES',
  LOAD_POPULAR_SHOWS: 'LOAD_POPULAR_SHOWS',
  LOAD_SIMILAR_MOVIES: 'LOAD_SIMILAR_MOVIES',
  LOAD_SIMILAR_SHOWS: 'LOAD_SIMILAR_SHOWS'
}

export default actionTypes
