const actionTypes = {
  LOAD_ERROR: 'LOAD_ERROR',
  HIDE_ERROR: 'HIDE_ERROR',
  LOAD_POPULAR_MOVIES: 'LOAD_POPULAR_MOVIES',
  LOAD_SIMILAR_MOVIES: 'LOAD_SIMILAR_MOVIES',
  LOAD_MOVIE_DETAIL: 'LOAD_MOVIE_DETAIL',
  LOAD_POPULAR_SHOWS: 'LOAD_POPULAR_SHOWS',
  LOAD_SIMILAR_SHOWS: 'LOAD_SIMILAR_SHOWS',
  LOAD_SHOW_DETAIL: 'LOAD_SHOW_DETAIL'
}

export default actionTypes
